#!/usr/bin/env bun

import type { BunPlugin } from "bun"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const rootDir = path.resolve(__dirname, "../../..")

// Load solidPlugin from root's node_modules (monorepo layout)
import solidPlugin from "../../../node_modules/@opentui/solid/scripts/solid-plugin"

process.chdir(dir)

const dedupePlugin: BunPlugin = {
  name: "dedupe-opentui",
  setup(build) {
    // Use root's node_modules (monorepo layout)
    const rootNodeModules = path.resolve(rootDir, "node_modules")
    const solidPath = path.resolve(rootNodeModules, "@opentui/solid/index.js")
    const corePath = path.resolve(rootNodeModules, "@opentui/core/index.js")
    const coreDir = path.resolve(rootNodeModules, "@opentui/core")

    // Verify paths exist before using them
    if (!fs.existsSync(solidPath)) {
      console.warn(`Warning: @opentui/solid not found at ${solidPath}`)
    }
    if (!fs.existsSync(corePath)) {
      console.warn(`Warning: @opentui/core not found at ${corePath}`)
    }

    // Dedupe @opentui/solid and @opentui/core to use the same instance
    build.onResolve({ filter: /^@opentui\/solid$/ }, () => ({ path: solidPath }))
    build.onResolve({ filter: /^@opentui\/core$/ }, () => ({ path: corePath }))

    // Handle subpath exports for @opentui/core (e.g., @opentui/core/testing)
    build.onResolve({ filter: /^@opentui\/core\/.*/ }, (args) => {
      const subpath = args.path.substring("@opentui/core".length) // e.g., "/testing"
      const exported = path.resolve(coreDir, subpath.slice(1) + ".js") // e.g., "testing.js"
      if (fs.existsSync(exported)) {
        return { path: exported }
      }
      return undefined // Let Bun resolve normally if not found
    })

    // Also handle @opentui/solid subpaths if needed
    build.onResolve({ filter: /^@opentui\/solid\/.*/ }, (args) => {
      const subpath = args.path.substring("@opentui/solid".length) // e.g., "/something"
      const solidDir = path.resolve(rootNodeModules, "@opentui/solid")
      const exported = path.resolve(solidDir, subpath.slice(1) + ".js")
      if (fs.existsSync(exported)) {
        return { path: exported }
      }
      return undefined
    })
  },
}

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(rootDir, "node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [dedupePlugin, solidPlugin],
    sourcemap: "external",
    minify: true,
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`
}

export { binaries }
